### ISSUE TITLE
eslint报错

### ISSUE THREAD

**Issue by qinze118** [wilsonIs/vue-treeSelect#15]
大神好：
我直接使用你的src放到组件中启动项目报错，应该是es版本的问题吧。
✘ 70 problems (70 errors, 0 warnings)

Errors:
  66  http://eslint.org/docs/rules/semi
   4  http://eslint.org/docs/rules/no-extra-semi

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by wilsonIs** [comment]
@qinze118 这个组件没有设eslint规则，写的比较个人风格。
你可以按照你设置的eslint规则把代码改一改哈

**Comment by qinze118** [comment]
好的，谢谢！@wilsonIs
