### ISSUE TITLE
Can I use the callback function in events to block updates （select,deselect）?

### ISSUE THREAD

**Issue by I3NLi** [wilsonIs/vue-treeSelect#16]
First of all, I want to thank you for the awesome you provided.
I want to check the select/deselect and block the update under certain conditions.
I have tried returning false in select/deselect, but it doesn't work.
Is this feature supported?
if not, do you have any suggestions for me to implement it (specifically on deselect)?

**Comment by wilsonIs** [comment]
It's not supported. Maybe you can set a beforeClick promise callback to handle that.
