### ISSUE TITLE
v-model的值为什么不是双向绑定呢

### ISSUE THREAD

**Issue by lerit** [wilsonIs/vue-treeSelect#3]
不知道我的理解对否，我觉得v-model就是实现双向绑定的，否则就用一个普通属性了。
可是我发现这个值并没有被更新，而是通过手动添加setSelectedId让用户来更新；这是有什么别的考虑吗？
谢谢。

**Comment by wilsonIs** [comment]
@lerit 主要是因为实际操作中，经常需要在数据改变的回调函数中进行某些其他的操作，所以会单独的拿出来。
而且子组件向父组件传值是通过emit进行的，这个和v-model双向绑定没有关系

**Comment by lerit** [comment]
谢谢你的回复

**Comment by FullOfVigour** [comment]
我测试了一下发现删除 v-model 之后基本无障碍运行,这样的 v-model 还设置着有什么用?
