### ISSUE TITLE
咨询下，这个要怎么用呢？怎么把他用在我的项目中呢？

### ISSUE THREAD

**Issue by zq99299** [wilsonIs/vue-treeSelect#4]
咨询下，这个要怎么用呢？怎么把他用在我的项目中呢？

**Comment by wilsonIs** [comment]
@zq99299 直接把封装好的组件挪过去  应该就可以用了

**Comment by zq99299** [comment]
直接全部拿过去是可以用，就是文件太多了。
昨天研究了一天怎么写自己的组件库并发布到npm中，已经参考iview的源码结构搭建了开发环境和打包的配配置，打包的配置正在记录中，链接如下，互相学习
https://zq99299.gitbooks.io/vue-note/content/chapter/vu_components_lib/
