### ISSUE TITLE
选中的值打印为undefined？

### ISSUE THREAD

**Issue by Kanchil** [wilsonIs/vue-treeSelect#5]
![image](https://user-images.githubusercontent.com/20110220/29668780-f2ca4fd6-8913-11e7-84a0-4c7bdf8531e8.png)
![image](https://user-images.githubusercontent.com/20110220/29668789-f8249cc0-8913-11e7-99b4-2427e96f2212.png)

**Comment by bigbear1007** [comment]
treeProps:{
          label: "name",
          children: "children",
          level:"treeLevel"
        }
发出来看看这个配置
