### ISSUE TITLE
网络请求后，给treeData赋值，treeSelect下拉为空

### ISSUE THREAD

**Issue by Kanchil** [wilsonIs/vue-treeSelect#6]

**Comment by Kanchil** [comment]
![image](https://user-images.githubusercontent.com/20110220/29702233-eba94574-89a2-11e7-9946-cf2ede75cecd.png)
![image](https://user-images.githubusercontent.com/20110220/29702248-fa26e124-89a2-11e7-8650-c8a1698254ed.png)

**Comment by bigbear1007** [comment]
treeProps:{
          label: "name",
          children: "children",
          level:"treeLevel"
        }
这个地方要配置

**Comment by Kanchil** [comment]
![image](https://user-images.githubusercontent.com/20110220/29702794-53839dc8-89a5-11e7-9b42-5792f96f87e1.png)

**Comment by Kanchil** [comment]
在data()里面对categoryOpt进行赋值的话，下拉框中是有值的，但是请求数据重新赋值后，就是空的了！

**Comment by bigbear1007** [comment]
没有level能用？

**Comment by Kanchil** [comment]
![image](https://user-images.githubusercontent.com/20110220/29703041-7b31eb44-89a6-11e7-937a-cd1374978a4e.png)
![image](https://user-images.githubusercontent.com/20110220/29703047-87089652-89a6-11e7-995a-075f0979b776.png)

**Comment by Kanchil** [comment]
加上这个配置后也不行

**Comment by bigbear1007** [comment]
走查一遍代码，不行重新复制粘贴吧。。

**Comment by Kanchil** [comment]
哦

**Comment by Kanchil** [comment]
已经解决了！很是感谢。哈哈

**Comment by Kanchil** [comment]
![image](https://user-images.githubusercontent.com/20110220/29706559-ca8102d0-89b4-11e7-885f-da0df6bcff64.png)

**Comment by wilsonIs** [comment]
@Kanchil 😄
